### ISSUE TITLE
Composer issue, package require nette/utils

### ISSUE THREAD

**Issue by vasilvestre** [nunomaduro/phpinsights#56]
My composer.json do not have nette/utils or object-calisthenics/phpcs-calisthenics-rules dependency

```bash
Using version ^1.0 for nunomaduro/phpinsights
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nette/utils (locked at v3.0.1) -> satisfiable by nette/utils[v3.0.1].
    - nunomaduro/phpinsights v1.0.0 requires object-calisthenics/phpcs-calisthenics-rules ^3.5 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.5.0].
    - nunomaduro/phpinsights v1.0.1 requires object-calisthenics/phpcs-calisthenics-rules ^3.5 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.5.0].
    - nunomaduro/phpinsights v1.0.2 requires object-calisthenics/phpcs-calisthenics-rules ^3.5 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.5.0].
    - nunomaduro/phpinsights v1.0.3 requires object-calisthenics/phpcs-calisthenics-rules ^3.5 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.5.0].
    - nunomaduro/phpinsights v1.0.4 requires object-calisthenics/phpcs-calisthenics-rules ^3.5 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.5.0].
    - nunomaduro/phpinsights v1.0.5 requires object-calisthenics/phpcs-calisthenics-rules ^3.5 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.5.0].
    - Conclusion: don't install object-calisthenics/phpcs-calisthenics-rules v3.5.0
    - Installation request for nunomaduro/phpinsights ^1.0 -> satisfiable by nunomaduro/phpinsights[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5].

Installation failed, reverting ./composer.json to its original content.
```

**Comment by BlackHades** [comment]
In my own case i had this error because i had phpstan in my require-dev, once i removed it, nunomaduro/phpinsights installed fine.

another fix is to add "nette/utils": "^2.5" to your composer.json file in the require-dev section, and run composer update. I hope this helps.

**Comment by vasilvestre** [comment]
> In my own case i had this error because i had phpstan in my require-dev, once i removed it, nunomaduro/phpinsights installed fine.

I want to keep my phpstan ahah

> another fix is to add "nette/utils": "^2.5" to your composer.json file in the require-dev section, and run composer update. I hope this helps.

```
vsilvestre@VSILVE-3520-L:~/Projets/api$ dce php composer require "nette/utils:^2.5"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nette/bootstrap v3.0.0 requires nette/utils ^3.0 -> satisfiable by nette/utils[3.0.x-dev, v3.0.0, v3.0.0-RC1, v3.0.0-beta1, v3.0.0-beta2, v3.0.1] but these conflict with your requirements or minimum-stability.
    - nette/bootstrap v3.0.0 requires nette/utils ^3.0 -> satisfiable by nette/utils[3.0.x-dev, v3.0.0, v3.0.0-RC1, v3.0.0-beta1, v3.0.0-beta2, v3.0.1] but these conflict with your requirements or minimum-stability.
    - nette/bootstrap v3.0.0 requires nette/utils ^3.0 -> satisfiable by nette/utils[3.0.x-dev, v3.0.0, v3.0.0-RC1, v3.0.0-beta1, v3.0.0-beta2, v3.0.1] but these conflict with your requirements or minimum-stability.
    - Installation request for nette/bootstrap (locked at v3.0.0) -> satisfiable by nette/bootstrap[v3.0.0].
```
Doesn't work :/

**Comment by danielspk** [comment]
Same problem, I also have installed PHPStan in --dev.

**Comment by rayblair06** [comment]
Similar issue but with "nunomaduro/larastan", which uses PHPStan.

Uninstalling "nunomaduro/larastan", installing "nunomaduro/phpinsights" then reinstalling "nunomaduro/larastan" on top seems to have fixed the issue.

**Comment by kenowessels** [comment]
> Uninstalling "nunomaduro/larastan", installing "nunomaduro/phpinsights" then reinstalling "nunomaduro/larastan" on top seems to have fixed the issue.

works for me with "phpstan/phpstan" instead of "nunomaduro/larastan"

**Comment by axelitus** [comment]
I'm having this issue also.

```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nette/utils (locked at v3.0.1) -> satisfiable by nette/utils[v3.0.1].
    - nunomaduro/phpinsights v1.0.0 requires object-calisthenics/phpcs-calisthenics-rules ^3.5 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.5.0].
    - nunomaduro/phpinsights v1.0.1 requires object-calisthenics/phpcs-calisthenics-rules ^3.5 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.5.0].
    - nunomaduro/phpinsights v1.0.2 requires object-calisthenics/phpcs-calisthenics-rules ^3.5 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.5.0].
    - nunomaduro/phpinsights v1.0.3 requires object-calisthenics/phpcs-calisthenics-rules ^3.5 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.5.0].
    - nunomaduro/phpinsights v1.0.4 requires object-calisthenics/phpcs-calisthenics-rules ^3.5 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.5.0].
    - nunomaduro/phpinsights v1.0.5 requires object-calisthenics/phpcs-calisthenics-rules ^3.5 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.5.0].
    - Conclusion: don't install object-calisthenics/phpcs-calisthenics-rules v3.5.0
    - Installation request for nunomaduro/phpinsights ^1.0 -> satisfiable by nunomaduro/phpinsights[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5].


Installation failed, reverting ./composer.json to its original content.
```

My require-dev looks like:

```json
"require-dev": {
    "phpstan/phpstan": "^0.11",
    "phpunit/phpunit": "^8.1",
    "squizlabs/php_codesniffer": "^3.4"
},
```

Removing `"phpstan/phpstan": "^0.11"` and `"squizlabs/php_codesniffer": "^3.4"` doesn't solve my problem. I'm not able to install PHPInsights.

**Comment by garak** [comment]
I also managed to install by removing phpstan and then re-adding it

**Comment by nunomaduro** [comment]
This should be fixed soon: https://github.com/object-calisthenics/phpcs-calisthenics-rules/issues/90.

**Comment by vasilvestre** [comment]
https://github.com/object-calisthenics/phpcs-calisthenics-rules/issues/90
Look like it's now fixed! Someone could confirm so I close this ? :D

**Comment by axelitus** [comment]
I can check on a project I'm working on, just give me an hour to get to the office and test.

**Comment by nunomaduro** [comment]
It's not fixed, the issue still exists. You should use the latest version php insights 1.2

**Comment by axelitus** [comment]
Indeed, @nunomaduro is right, it is still not fixed. I'm still getting this error:

```bash
Using version ^1.2 for nunomaduro/phpinsights
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symplify/coding-standard v5.4.16 requires symplify/better-phpdoc-parser ^5.4.16 -> satisfiable by symplify/better-phpdoc-parser[5.5.x-dev, v5.4.16].
    - symplify/better-phpdoc-parser 5.5.x-dev requires symplify/package-builder ^5.5 -> satisfiable by symplify/package-builder[5.5.x-dev].
    - Can only install one of: symplify/package-builder[v5.4.16, 5.5.x-dev].
    - nunomaduro/phpinsights v1.2.0 requires symplify/coding-standard 5.4.16 -> satisfiable by symplify/coding-standard[v5.4.16].
    - nunomaduro/phpinsights v1.2.0 requires symplify/package-builder 5.4.16 -> satisfiable by symplify/package-builder[v5.4.16].
    - Installation request for nunomaduro/phpinsights ^1.2 -> satisfiable by nunomaduro/phpinsights[v1.2.0].
    - Conclusion: remove nette/utils v3.0.1
    - Conclusion: don't install nette/utils v3.0.1
    - symplify/better-phpdoc-parser v5.4.16 requires nette/utils ^2.5 -> satisfiable by nette/utils[v2.5.0, v2.5.1, v2.5.2, v2.5.3, v2.5.x-dev].
    - Can only install one of: nette/utils[v2.5.0, v3.0.1].
    - Can only install one of: nette/utils[v2.5.1, v3.0.1].
    - Can only install one of: nette/utils[v2.5.2, v3.0.1].
    - Can only install one of: nette/utils[v2.5.3, v3.0.1].
    - Can only install one of: nette/utils[v2.5.x-dev, v3.0.1].
    - Installation request for nette/utils (locked at v3.0.1) -> satisfiable by nette/utils[v3.0.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by tyler36** [comment]
> Uninstalling "nunomaduro/larastan", installing "nunomaduro/phpinsights" then reinstalling "nunomaduro/larastan" on top seems to have fixed the issue.

@rayblair06 worked for me, thanks

**Comment by nunomaduro** [comment]
This issue has been fixed on the version `v1.5.0`.
